### ISSUE TITLE
Installation without http:// access

### ISSUE THREAD

**Issue by RainerHeintzmann** [ahnlabb/BioformatsLoader.jl#14]
I tried to install BioformatsLoader on a Linux high performance cluster and have the problem that I do no have http:// access. However, I can copy the bioformats.jar file onto the machine by other means. Is there a way to tell the `build` command where to find this resource and copy it from there?

**Comment by ahnlabb** [comment]
Right now easiest way would probably be to simply copy the necessary files into the package `deps` directory directly.

For example (needs to be adapted for your particular directories):
```sh
cp bioformats_package.jar ~/.julia/packages/BioformatsLoader/6wbxi/deps/
cp ome.xsd ~/.julia/packages/BioformatsLoader/6wbxi/deps/
```

as you can see from the build scripts the files can be found here:
- https://downloads.openmicroscopy.org/bio-formats/6.5.1/artifacts/bioformats_package.jar
- https://www.openmicroscopy.org/Schemas/OME/2016-06/ome.xsd

**Comment by RainerHeintzmann** [comment]
Thanks a lot for the quick reply! I try your suggestion. However, the build command still tries to download and fails.
If I ignore the build I run into the following problem:
```
julia> BioformatsLoader.init(); # Initializes JavaCall with opt and classpath
ERROR: JavaCall.JavaCallError("Class Not Found loci/common/DebugTools")
Stacktrace:
 [1] _metaclass(class::Symbol)
   @ JavaCall ~/.julia/packages/JavaCall/tjlYt/src/core.jl:383
 [2] metaclass(class::Symbol)
   @ JavaCall ~/.julia/packages/JavaCall/tjlYt/src/core.jl:389
 [3] jcall(typ::Type{JavaCall.JavaObject{Symbol("loci.common.DebugTools")}}, method::String, rettype::Type, argtypes::Tuple{DataType}, args::String)
   @ JavaCall ~/.julia/packages/JavaCall/tjlYt/src/core.jl:225
 [4] enableLogging(level::String)
   @ BioformatsLoader ~/.julia/packages/BioformatsLoader/vuByl/src/BioformatsLoader.jl:230
 [5] init(; memory::Int64, log_level::String)
   @ BioformatsLoader ~/.julia/packages/BioformatsLoader/vuByl/src/BioformatsLoader.jl:238
 [6] init()
   @ BioformatsLoader ~/.julia/packages/BioformatsLoader/vuByl/src/BioformatsLoader.jl:236
 [7] top-level scope
   @ REPL[2]:1
```

**Comment by ahnlabb** [comment]
Yes, the build command will still fail, once again this would probably be better solved by artifacts. However, the error on `BioformatsLoader.init()` definitely seems to indicate that the `bioformats_package.jar` is not in the deps directory. Can you verify that the path returned by `BioformatsLoader.get_bf_path()` looks like the path where you copied the jar file and that `isfile(BioformatsLoader.get_bf_path())` returns `true`?

**Comment by RainerHeintzmann** [comment]
Sorry. You are absolutely right. One of the files did not arrive at the location where I wanted to copy it to.
Now it all works nicely!
