### ISSUE TITLE
Ctrl-C can quit Julia

### ISSUE THREAD

**Issue by timholy** [ahnlabb/BioformatsLoader.jl#18]
I noticed that hitting Ctrl-C while in the middle of an operation can often lead to Julia just silently quitting. I thought to myself that `disable_sigint` wrappers might help, but they didn't seem to. @ahnlabb, have you seen this, and do you have any understanding of where it comes from?

**Comment by ahnlabb** [comment]
This should be fixable. I've encountered it but not thought too much about it since it is somewhat expected when running the JVM as a service this way.

We should probably pass `-Xrs` ([reference](https://docs.oracle.com/javase/8/docs/technotes/tools/unix/java.html)). It has certain implications and should perhaps be added to JavaCall.jl instead.

I will have a closer look when I'm back from vacation in a week but in the meantime adding `-Xrs` to the options in the `JavaCall.init` call inside `BioformatsLoader.init` makes sense. If you try it and it fixes the problem (perhaps in combination with `disable_sigint`) please open a PR.

**Comment by ahnlabb** [comment]
This should now be fixed (084efe79b7c4f9d679fcee0f44bf18c972b679b2).

Let me know if it seems to be working for you @timholy.  I'm still not certain whether we need `disable_sigint`, seems like we could possibly leak memory if we allow interruptions in the middle of a call through JNI but this should probably me investigated in [JuliaInterop/JavaCall.jl](https://github.com/JuliaInterop/JavaCall.jl). I'm opening an issue there now.

**Comment by mkitti** [comment]
To allow multiple Java-based packages for Julia to interoperate, I recommend:

1. Adding the classpath via `JavaCall.addClassPath` at the Julia module `__init__`. For example, see this from View5D.jl: https://github.com/RainerHeintzmann/View5D.jl/blob/master/src/View5D.jl#L77-L87

2. Similarly, use `JavaCall.addOpts` either through the Juila module `__init__` or through a distinct method such as `BioformatsLoader.addOpts()` that someone else could invoke to help setup up the JVM options.

3. Checking `JavaCall.isloaded()` before invoking `JavaCall.init()` on `BioformatsLoader.init()`. For example, https://github.com/RainerHeintzmann/View5D.jl/blob/master/src/View5D.jl#L1289-L1293

The proposed flow is as follows for two or more packages which use JavaCall:
```julia
using View5D # Adds View5D classpath and necessary options via `View5D.__init__()`
using BioformatsLoader # Add BioformatsLoader classpath and necessary options via `BioformatsLoader.__init__()`
import JavaCall

JavaCall.addOpts( ... ) # User specific options
JavaCall.addClassPath( ... ) # User specific classpath

JavaCall.init() # Initialize JVM with options built by `JavaCall.addClassPath` and `JavaCall.addOpts` above
```

Having a `BioformatsLoader.init()` is fine as well but the classpath should have already been added by `BioformatsLoader.__init__()`.

**Comment by timholy** [comment]
> Let me know if it seems to be working for you @timholy

Yes, it's working and it's much nicer! Thanks very much.

**Comment by timholy** [comment]
@mkitti, the only bad thing about that workflow is that it would be ideal if I didn't have to mess with remembering to call `init`. In the rest of my world, packages are ready to go as soon as I load them. I understand that Java may make that harder/impossible, but perhaps the best thing would be some kind of user-level configuration file that can be parsed in the `__init__` method of various packages to set all needed options/classpaths/whatever.

**Comment by mkitti** [comment]
> @mkitti, the only bad thing about that workflow is that it would be ideal if I didn't have to mess with remembering to call `init`.

One could automate `init` by being lazy and having this package's public API invoke it just before someone tries to load an image. You would need to add a call to `init` from `open_img`, `open_stack`, `bf_import`, etc. With the change in 084efe7, the overhead should just be checking the boolean value in the Ref for subsequent calls to `init`.

This is essentially how recent versions of GR now work:
https://github.com/jheinen/GR.jl/blob/143a9c1113e101f2f0ec9212dab4841eb9f89130/src/funcptrs.jl#L72-L78
Each low-level public API function invokes `libGR_ptr`. That invokes `get_func_ptr`, which invokes `load_libs` on the first invocation only. The external library is not loaded until the user actually tries to plot something with GR. Part of the reason for that is the user may choose to switch to a different Plots.jl backend before choosing GR.

In the Java space, we now have several Java packages for Julia, but the JVM can only be initialized once. If every package initialized the JVM on `__init__` that would prevent the various Java packages for Julia from interoperating with each other.

I think https://github.com/JuliaPackaging/Preferences.jl offers that user configuration file facility. However, I do not think that is exclusive to packages adding some configuration at package `__init__` while deferring JVM `init` to later.
