### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by RainerHeintzmann** [ahnlabb/BioformatsLoader.jl#25]
Can a new release be made, or is something missing before this should be done?
I would have asked in "Discussions", but this seems not to be activated for this repository.

**Comment by RainerHeintzmann** [comment]
... if you sketch the user interface changes you envisioned, I might be able to help you.

**Comment by ahnlabb** [comment]
Thanks! I've pushed a basic implementation of the direction I'm envisioning to the [feat/bfreader](/ahnlabb/BioformatsLoader.jl/tree/feat/bfreader) branch. It shows the principle but needs to be simplified, documented, tested and used throughout the code. The general idea is that functions such as `get_num_sets` and `metadata` should not really be necessary if we provide a more flexible reader. The `subidx` and `subset` change is really a special case of "I want more granular control over import" and sometimes you might want to change how you read based on metadata or even (perhaps rarely) based on image data. I'm currently thinking that we keep all exported functions as conveniences but use the mid-level abstraction of `BFReader` underneath.
