### ISSUE TITLE
Register this package

### ISSUE THREAD

**Issue by mkitti** [ahnlabb/BioformatsLoader.jl#6]
I would like to have this package in the Julia registry. Would you like to do so or would you mind if I registered it?

**Comment by ahnlabb** [comment]
Thank you for reminding me @mkitti. I agree that it should be registered. I'll get to it this week.

**Comment by mkitti** [comment]
Here is a reference: https://github.com/JuliaRegistries/Registrator.jl/blob/master/README.md

**Comment by ahnlabb** [comment]
This issue is currently blocked by the issues with the OME website ( [image.sc thread](https://forum.image.sc/t/ome-resources-down-due-to-uod-outage/43957), [University of Dundee system status ](https://www.uodit.info/)). Registration will be retriggered once these have been resolved.

**Comment by mkitti** [comment]
Thanks for the update!

**Comment by ahnlabb** [comment]
Fixed by JuliaRegistries/General#22789.
